title: wizard.screenly.io
email: hello@screenlyapp.com
description: >-
  A tool for configuring network settings in Screenly Pro.
baseurl: ""
url: ""
twitter_username: screenlyapp
github_username:  screenly

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
